export const Person = {
    modelName: 'Person',
    id,
    login,
    avatar,
    fullName,
    groupName,
    projectName,
    positionName,
    workTypeName,
    sex,
    dateOfBirth,
    phone,
    email,
    telegram,
}